project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - presentation/overview.qmd
description-meta: "Infectious Disease Research & Epidemiology | Wake Forest School of Medicine"

website:
  favicon: assets/logo.png
  title: "Malaria Control Strategy Lab"
  navbar:
    pinned: true
    background: primary
    title: Malaria Control Strategy Lab
    logo: assets/logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Simulation Lab"
        href: docs/malaria-simulator.html
      - text: "Vector Environment Lab"
        href: docs/vectors.html
      - text: "Pharmacology Lab"
        href: docs/pharmacokinetics.html
      - text: "Diagnostics Lab"
        href: docs/diagnostics.html
      - text: "Vaccine Design Lab"
        href: docs/vaccine-design.html
      - text: "Lecture Presentation"
        href: presentation/overview.qmd
    page-footer:
      center:
      - text: "Disclaimer"
        href: disclaimer.qmd


format:
  html:
    toc: true
    code-copy: true
    code-overflow: wrap
    theme: [cerulean, theme.scss]
    css: assets/styles.css